Transform: AWS::Serverless-2016-10-31

Resources:
  TelescopeElasticsearch:
    Type: AWS::Lambda::Function
    Properties:
      Code: ../../src
      FunctionName: telescope-elasticsearch
      Handler: handler.lambda_handler
      Role: TelescopeElasticsearchRole
      Runtime: python3.8
